version: '3'

services:
  master:
    image: locustio/locust:master
    ports:
     - "8089:8089"
    volumes:
      - .:/mnt/locust
    command: -f /mnt/locust/test/task/hooks --master --web-host=0.0.0.0
  
  worker:
    image: locustio/locust:master
    volumes:
      - .:/mnt/locust
    command: -f /mnt/locust/test/task/hooks --worker --master-host master